### ISSUE TITLE
No annotation for demo mgf file

### ISSUE THREAD

**Issue by j-a-dietrich** [Philipbear/msbuddy#3]
Hello, 
when I run the code from the quick start section for the formula annotation I don't get any annotation for the spectra. As input I used the provided demo mgf file. 

![MSBuddyAnnotationNotWorking](https://github.com/Philipbear/msbuddy/assets/149300241/80f5d8a3-264d-4ace-a881-0da62c19b831)

Any ideas why it doesn't work?

**Comment by Philipbear** [comment]
Hello,

First, please upgrade the msbuddy to v0.3.1. There are some known issues with the previous versions. Sorry about the inconvenience.

Please let me know if this remains after package upgrade.

**Comment by j-a-dietrich** [comment]
I upgrade from v0.2.9 to v0.3.1 but still have the same problem.

**Comment by Philipbear** [comment]
It looks like there is something wrong with the database initialization.

1. Did you see any progress bar indicating the database download (three in total)? this should happen during the first time you use msbuddy.

2. Could you please go to the file location where the msbuddy package is installed? Check if there is a 'data' folder within the msbuddy package. They should be of 68KB, 436MB and 426MB.
<img width="270" alt="image" src="https://github.com/Philipbear/msbuddy/assets/50896636/4bea4a4a-c513-48b1-818b-5d9fb87bedf8">

Thanks for the patience and feedback. This really helps me to improve the package.

**Comment by j-a-dietrich** [comment]
Yes, I saw a progress bar and the following joblib files are stored in the msbuddy data folder:
![MSbuddyDatabases](https://github.com/Philipbear/msbuddy/assets/149300241/ffab9aae-fe68-4615-8274-e6eaa70103f7)

**Comment by Philipbear** [comment]
Hi,

I tried to repeat your case but found no issue.
Here is a msbuddy quick start on [GoogleColab](https://colab.research.google.com/drive/1jFnuzSssxMJtd29lrQwPOBs-qUzmKAic?usp=sharing). It runs well.

In this case, I'd suggest you recreate a new python environment probably.

**Comment by j-a-dietrich** [comment]
I created a new conda environment and still didn't get any results on my Windows laptop. Since it worked in Google Colab, I switched to a MacBook (Intel) and replicated the installation I used on my Windows laptop, and here it works perfectly fine. It seems to be Windows-related or did you get it running on a Windows laptop?

**Comment by Philipbear** [comment]
It turns out be the timeout_decorator package not working well on Windows. I have solved the issue and released the msbuddy v0.3.2.

Thanks for raising this!
