### ISSUE TITLE
Question about ADDUCT

### ISSUE THREAD

**Issue by mansoldof** [Philipbear/msbuddy#4]
Dear Shipei Xing,
Congratulations for this great work!

Is there any way to inform the adduct in the MGF per ion? something like:
ADDUCT=[M+Cl]-
IONMODE= Negative
Or by command line?

If this alternative is not possible, it would be possible to loop through each ion of the mgf and do something like:
per ion:
engine.add_data( MetaFeature(identifier = ion_id , mz = PEPMASS, adduct = "[M+Cl]-", charge=-1) )

Or some other possibility?

thank you

**Comment by Philipbear** [comment]
Hi Felipe, Thanks.

Yes to your question. I just made an update (version 0.3.8). It now reads 'ADDUCT=[M+Cl]-'. Other than 'ADDUCT', the following field names in mgf are also regarded as fields for adduct types: ION, ION_TYPE, ADDUCT_TYPE.

It is also possible to add adduct types in the loop as you mentioned.

Feel free to let me know if adducts are not read correctly in MGF. Thanks for reaching out.

**Comment by mansoldof** [comment]
Thank you, I will test and let you know,
my best
