### ISSUE TITLE
Cannot install on Python version 3.13.0

### ISSUE THREAD

**Issue by Kuan-Wei** [Philipbear/msbuddy#5]
Just a little problem when I try to install your software. 
```
RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
```

**Comment by Philipbear** [comment]
Thanks. It turns out that numba package does not support python 3.13 yet.

See [here](https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information) for more details.

Thanks for pointing it out, and please use python >= 3.9 and <3.13.

Shipei
